name: CV
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.2.1
  - conda-pack
  - cudatoolkit=11.8.0
  - pytorch 
  - torchvision 
  - torchaudio 
  - pytorch-cuda=11.8 
  - pandas
  - scikit-learn 
  - scikit-image 
  - matplotlib
  - pylint
  - gradio
  - urllib3=1.26.16
  - MarkupSafe=2.1.3  
  - pip:
      - nvidia-pyindex
      - nvidia-cudnn-cu11==8.9.4.25 
      - tensorflow<2.11
      - opencv-python   
            
# conda env create -f environment.yaml